name: Create Tar.gz Archive for OTA Updates

on:
  push:
    branches:
      - main

jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Tar.gz Archive
      run: |
        tar -czvf firmware.tar.gz outside_station/software/src/*


    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: archive
        path: outside_station/software/firmware.tar.gz
