name: Create tar.gz Archive for OTA Updates
run-name: ${{ github.actor }} - Create tar.gz Archive for OTA Updates

on:
  push:
    paths:
      - 'outside_station/software/src/**'

permissions:
  contents: write

jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Remove old archive
      run: |
        rm -f outside_station/software/firmware.tar.gz

    - name: Create Tar.gz Archive
      run: |
        tar -czvf outside_station/software/firmware.tar.gz -C outside_station/software/src .

    - name: Commit the generated archive
      uses: EndBug/add-and-commit@v9
      with:
        add: 'outside_station/software/firmware.tar.gz'
        default_author: github_actions
